## Image classification with Convolutional Neural Networks

In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# This file contains all the main external libs we'll use
from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

from pathlib import Path

In [3]:
if os.name == 'nt':
    PATH = str(Path.home()) + "\\Development\\kaggle\\dogscats\\data\\"
else:
    PATH = "data/dogscats/"
    
sz=224
arch=vgg16
bs=64

In [4]:
# Uncomment the below if you need to reset your precomputed activations
if os.name == 'nt':
    ## warning: will remove everything under the following path (windows):
    #delPath = f"{PATH}tmp\\"
    #!rmdir /S /Q "{delPath}"
    ;
else:
    #!rm -rf {PATH}tmp
    ;

In [5]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))

In [6]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [7]:
%time learn.fit(0.01, 3, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.05655  0.03412  0.98754]                                                                                                                                      
[ 1.       0.05506  0.03137  0.98853]                                                                                                                                      
[ 2.       0.04297  0.02938  0.98972]                                                                                                                                      

Wall time: 8.69 s


In [8]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)

In [9]:
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs, num_workers=4)
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [10]:
learn.fit(1e-2, 2)

HBox(children=(IntProgress(value=0, description='Epoch', max=2), HTML(value='')))

[ 0.       0.04514  0.03067  0.98972]                                                                                                                                      
[ 1.       0.05125  0.03157  0.98932]                                                                                                                                      



In [11]:
learn.precompute=False

In [12]:
%time learn.fit(1e-2, 1, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=1), HTML(value='')))

[ 0.       0.05378  0.02791  0.9907 ]                                                                                                                                      

Wall time: 2min 2s


In [13]:
learn.unfreeze()

In [14]:
lr=np.array([1e-4,1e-3,1e-2])

In [15]:
%time learn.fit(lr, 1, cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=1), HTML(value='')))

[ 0.       0.06328  0.0303   0.98952]                                                                                                                                      

Wall time: 4min 45s


In [16]:
%time learn.fit(lr, 3, cycle_len=1, cycle_mult=2)

HBox(children=(IntProgress(value=0, description='Epoch', max=7), HTML(value='')))

[ 0.       0.04292  0.0282   0.99031]                                                                                                                                      
[ 1.       0.04018  0.02556  0.99248]                                                                                                                                      
[ 2.       0.05903  0.02746  0.9913 ]                                                                                                                                      
[ 3.       0.05055  0.02341  0.99189]                                                                                                                                      
[ 4.       0.04312  0.02636  0.99051]                                                                                                                                      
[ 5.       0.0237   0.02283  0.99229]                                                                                                       

In [17]:
%time learn.fit(lr, 3, cycle_len=3)

HBox(children=(IntProgress(value=0, description='Epoch', max=9), HTML(value='')))

[ 0.       0.02367  0.02306  0.99367]                                                                                                                                      
[ 1.       0.0216   0.02256  0.99367]                                                                                                                                      
[ 2.       0.01934  0.02322  0.99367]                                                                                                                                      
[ 3.       0.02164  0.02303  0.99328]                                                                                                                                      
[ 4.       0.01724  0.02261  0.99426]                                                                                                                                      
[ 5.       0.02498  0.02316  0.99347]                                                                                                       

In [44]:
log_preds,y = learn.TTA()
accuracy(log_preds,y)

0.99223571570774438